---
- name: Install and deploy Couchbase
  hosts: all
  sudo: yes
  tasks:
  - name: Install selinux-python bindings
    yum: name=libselinux-python state=latest

  - name: Disable SELinux
    selinux: state=disabled

  - name: Install pkgconfig
    yum: name=pkgconfig state=latest

  - name: Install openssl
    yum: name=openssl098e state=latest

  - name: Check if Couchbase RPM exists
    stat: path=/vagrant/rpms/couchbase-server-enterprise-3.0.2-centos6.x86_64.rpm
    register: couchbase_rpm

  - name: Create RPMS Directory
    file: path=/vagrant/rpms state=directory
    when: couchbase_rpm.stat.exists == False

  - name: Download Couchbase RPM
    get_url: url=http://packages.couchbase.com/releases/3.0.2/couchbase-server-enterprise-3.0.2-centos6.x86_64.rpm dest=/vagrant/rpms/
    when: couchbase_rpm.stat.exists == False

  - name: Install current Couchbase RPM
    yum: name=/vagrant/rpms/couchbase-server-enterprise-3.0.2-centos6.x86_64.rpm state=present
