---
- name: Install ganglia server 
  yum: name={{item}} state=latest
  with_items:
    - ganglia-gmond
    - ganglia-gmetad
    - ganglia-web

- name: Configure apache to allow access to ganglia from everywere
  copy: src=ganglia/files/etc/httpd/conf.d/ganglia.conf dest=/etc/httpd/conf.d/ganglia.conf
  notify: restart apache

- name: Configure gemetad
  template: src=ganglia/templates/gmetad.conf.j2 dest=/etc/ganglia/gmetad.conf
  notify: restart gmetad

- name: Ensure httpd is running
  service: name=httpd state=started

- name: Ensure ganglia daemons are running
  service: name={{item}} state=started
  with_items:
    - gmond
    - gmetad
